version: '3'


services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./docker-services/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    container_name: appNginx
    depends_on: #запускать только если запущены нижние сервисы
      - php-fpm-8.1
      - php-fpm-7.4

  php-fpm-8.1:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/

  php-fpm-7.4:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/
